describe('Blogs', function() {
  it('shows blogs when logged in', function() {
    cy.visit('http://localhost:3000')
    cy.contains('Kirjautuminen')
    cy.get('#username')
      .type('Heikki')
    cy.get('#password')
      .type('Pulli')
    cy.contains('login')
      .click()
    cy.contains('Heikki logged in')
    cy.contains('Blogs')
    cy.contains('Näytä tiedot')
      .click()
    cy.contains('like')
      .click()
    cy.contains('poista blogi')

  })
})